import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/layout/Sidebar";
import FollowBar from "@/components/layout/FollowBar";
import LoginModal from "@/components/modals/LoginModal";
import RegisterModal from "@/components/modals/RegisterModel";
import {Toaster} from 'react-hot-toast'
import { NextAuthProvider } from "./providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params:{session,...params},
}: {
  children: React.ReactNode;
  params:any
}) {
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
        <Toaster/>
        <RegisterModal/>
        <LoginModal/>
        <div className="h-screen bg-black">
          <div className="container h-full mx-auto xl:px-30 max-w-6xl">
            <div className="grid grid-cols-4 h-full">
              <Sidebar />
              <div
                className="
                col-span-3 
              lg:col-span-2 
              border-x-[1px] 
              border-neutral-800
              "
              >
                {children}
              </div>
              <FollowBar />
            </div>
          </div>
        </div>
        </NextAuthProvider>
      </body>
    </html>
  );
}
